# Generated by Django 3.2.6 on 2021-10-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LokalApp', '0003_customer_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('total_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('cart_id', models.IntegerField()),
                ('dish_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LokalApp.product')),
            ],
        ),
    ]
