# Generated by Django 3.2.6 on 2021-10-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LokalApp', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
