# Generated by Django 3.2.6 on 2021-10-21 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LokalApp', '0005_auto_20211020_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
